const projects =
{
  "list": [
    {
      "no": 0,
      "orginal_no": 1,
      "title": "DV Administration Web system 2.1",
      "client": "Hamamatsu Photonics",
      "role": "Developer",
      "period": "Jul 2005 – Sep 2005",
      "teamSize": 4,
      "technologies": "C#, SQL Server, IIS, .Net Remoting",
      "description": "DVAdmin is a web system which is implemented for administrating real-time video streaming system. Web based interface for this application is developed in ASP.Net and java script. DVAdmin uses remoting features of C# and IIS for hosting.",
      "imageurl": "DVAdmin.webp"
    },
    {
      "no": 2,
      "orginal_no": 2,
      "title": "Mini TWAIN Scan to Folder Client",
      "client": "Hewlett-Packard",
      "role": "Developer",
      "period": "Oct 2005 - Nov 2005",
      "teamSize": 4,
      "technologies": "VC++",
      "description": "A Module that is used for TWAIN scanner. Scan to folder module helps a user to scan documents and pictures from scanner and save to folders and organize it.",
      "imageurl": "hp-scanjet-pro-2500-f1-flatbed-scanner-1.png"
    },
    {
      "no": 3,
      "orginal_no": 3,
      "title": "System Activity Monitor",
      "client": "Hamamatsu University",
      "role": "Developer",
      "period": "Dec 2005 – Mar 2006",
      "teamSize": 4,
      "technologies": "VC++, MySQL, API Hooking",
      "description": "System Activity Monitor (SAM) is software to control operation in Windows machines by accepting control from Administrator. SAM can be used for protecting valuable information by control opening, copying, deleting files and folders. SAM also keeps track of files that are used by a user and reports to administrator. Main use of this software is for schools and offices to protect their valuable information",
      "imageurl": "SAM.png"
    },
    {
      "no": 4,
      "orginal_no": 4,
      "title": "HP Device Integration Projects",
      "client": "Hewlett-Packard",
      "role": "Consultant, Team Leader, Developer",
      "period": "Mar 2006 – Jun 2012",
      "teamSize": 16,
      "technologies": "VC++, C#, Python, Install Shield, Clear Case, SVN, NANT, SQL Server, QTP",
      "description": "Integration of HP Device driver, applications and deployment was the main responsibly of the Integration team. Integration team manages build and release systems and also was responsible for Configuration management. Main part of this project is developing MSIs required for all devices and build MSIs. A development cycle for new products will contain 8-10 devices. There were programs to support older devices which need to support new Operating Systems that are introduced by Microsoft. The team integrated software and drivers for more than 150 All-in-One and single functions devices to support Windows Vista and Windows 7. ",
      "imageurl": "HPprinter.jpg"
    },
    {
      "no": 5,
      "orginal_no": 5,
      "title": "HP Karnak Software Integration",
      "client": "Hewlett-Packard",
      "role": "Team Leader",
      "period": "Feb 2009 – Aug 2010",
      "teamSize": 6,
      "technologies": "VC++, WIX, MS Build, Jenkins",
      "description": "Karnak was a program that introduced new generation software for Hewlett-Packard Imaging and Printing Group. Responsibility of the Karnak program was to build optimized and more user friendly software for HP All-in-One devices. Karnak program developed new printer, scanner and fax drivers. Also this program supported new features that are introduced in Microsoft Windows 7 like device stage.",
      "imageurl": "hp-karnak.webp"
    },
    {
      "no": 6,
      "orginal_no": 6,
      "title": "HP Web Registration Component",
      "client": "Hewlett-Packard",
      "role": "Consultant",
      "period": "Jun 2010 – Nov 2010",
      "teamSize": 3,
      "technologies": "VC++",
      "description": "HP Web Registration is a software that helps a user to register HP products very quickly so that user will get offers and protection from HP.",
      "imageurl": "webreg.webp"
    },
    {
      "no": 7,
      "orginal_no": 7,
      "title": "HP Tools & Services Project",
      "client": "Hewlett-Packard",
      "role": "Team Leader",
      "period": "Nov 2010 – Jun 2012",
      "teamSize": 10,
      "technologies": "Win32, MFC, COM, ATL, Winsock, DSF, WIX",
      "description": "Tools and services team was responsible for developing tools and host services that requires for HP software development team and HP customers. The team responsible for host builds and configuration tools as a service. One of the main responsibilities of the team was to build complete end-to-end automation for HP device software production.",
      "imageurl": "HP-Scan-doctor-1-1.webp"
    },
    {
      "no": 10,
      "orginal_no": 8,
      "title": "System1 Installer",
      "client": "General Electric Energy",
      "role": "Architect, Consultant",
      "period": "Jun 2012 – Dec 2012",
      "teamSize": 6,
      "technologies": "Win32, Install Shield 2012",
      "description": "An Installer that is used to deploy General Electric System1 software. Sytem1 is a software platform for industrial Optimization and Diagnostic Platform.",
      "imageurl": "gesystem1.jpeg"
    },
    {
      "no": 11,
      "orginal_no": 9,
      "title": "HP ConnectJet",
      "client": "Hewlett-Packard",
      "role": "Team Leader",
      "period": "Nov 2010 – Oct 2012",
      "teamSize": 7,
      "technologies": "C++, Win32, MFC, COM, ATL, Winsock, DSF, WIX",
      "description": "ConnectJet is a software to simulate multifunction Printer devices. ConnectJet helps developer to develop software for HP devices without having physical devices. It enabled HP to reduce the production cycle time. This project was a revolutionary innovation from Accel. ConnectJet helped Hewlett-Packard to able automated testes for USB and network devices which reduced cost of testing in a very large scale.\n",
      "imageurl": "hp-connectjet.png"
    },
    {
      "no": 8,
      "orginal_no": 10,
      "title": "HP - vSwitch Development and Certification",
      "client": "Hewlett-Packard",
      "role": "Team Leader",
      "period": "Jan 2013 – Mar 2013",
      "teamSize": 4,
      "technologies": "C++, VMware, OpenFlow",
      "description": "Virtual Network Distributed Switch is a virtual switch that was developed under VMware development environment that supports OpenFlow protocol.\n",
      "imageurl": "hp-vswitch.png"
    },
    {
      "no": 9,
      "orginal_no": 11,
      "title": "Tilera OpenFlow Switch",
      "client": "Tilera",
      "role": "Team Leader",
      "period": "Mar 2013 – Aug 2013",
      "teamSize": 5,
      "technologies": "C++, OpenFlow, Multicore Programming",
      "description": "An OpenFlow switch that is powered by multicore processor. Supports high speed switching using distributed multicore environment.\n",
      "imageurl": "tilera.png"
    },
    {
      "no": 12,
      "orginal_no": 12,
      "title": "TSP Integrations Installer SDK ",
      "client": "Product - Tyco",
      "role": "Team Leader",
      "period": "Aug 2013 – Jan 2104",
      "teamSize": 2,
      "technologies": "C#, WPF, WIX",
      "description": "An SDK for developers who works on CCURE 9000 and Victor integrations. Installer SDK is an add-in for Visual Studio which is a self-service tool for integrations developers. Developers will be able to create installers and build definition without help of Release Engineer.",
      "imageurl": "TycoCURE9000.png"
    },
    {
      "no": 13,
      "orginal_no": 13,
      "title": "Tyco - Victor Unified Site Server ",
      "client": "Product - Tyco",
      "role": "Developer",
      "period": "Nov 2013 – Jun 2014",
      "teamSize": 2,
      "technologies": "C#, WPF, Windows Embedded",
      "description": "Victor Unified Site Server is product of American Dynamics (A Tyco Company). We developed entire Windows 7 Embedded box with rich UI for CCURE9000 and NVR recorder.",
      "imageurl": "Tyco Prod_High Assurance Security Solution.png"
    },
    {
      "no": 14,
      "orginal_no": 14,
      "title": "Tyco - CCURE 9000 – Victor Unified Installer ",
      "client": "Product - Tyco",
      "role": "Team Leader",
      "period": "Dec 2013 – Sep 2015",
      "teamSize": 3,
      "technologies": "C#, WPF, WIX",
      "description": "WIX based installer for CCURE 9000 and Victor Unified product lines which includes the 16 integrations as well.",
      "imageurl": "TycoCURE9000.png"
    },
    {
      "no": 15,
      "orginal_no": 15,
      "title": "Tyco - Victor 4.7 Elasticity ",
      "client": "Product - Tyco",
      "role": "Developer",
      "period": "Sep 2014 – Sep 2015",
      "teamSize": 4,
      "technologies": "C#, WPF, WIX, VMWare, Azure Service Bus",
      "description": "Elasticity project was a major enhancement for Victor product lines to support distributed environment and automatic recovery from hardware failovers. Objective was to supporting n number of video recorders by configuring new recorders on the fly.",
      "imageurl": "tyco-victor.png"
    },
    {
      "no": 22,
      "orginal_no": 16,
      "title": "Cios-Fit Surgical Mobile C-Arm X-Ray System",
      "client": "SIEMENS",
      "role": "Architect, Technical Manager",
      "period": "Nov 2015 – Jan 2020",
      "teamSize": 20,
      "technologies": "C++, Qt 5.5, Qml, SQLite, MergeCOM, Freescale iMX6QP, Linux, TFS 2015, Jenkins",
      "description": "C-ARM is a brand new product development. The C ARM Dynamic UI Application is responsible\nfor displaying the UI and controlling the image queue. Application communicates with a GigE Vision\ncamera using ICMP to retrieve live images via shared memory and other IPC techniques.",
      "imageurl": "SIEMENS-cios_fit-v2.webp"
    },
    {
      "no": 20,
      "orginal_no": 17,
      "title": "SmartMedic – ICU Bed Monitoring Solution",
      "client": "Stryker ",
      "role": "Architect",
      "period": "March 2020 – July 2021",
      "teamSize": 10,
      "technologies": "C++, Qt 5.12, Qml, Angular, Node.js, Android, Azure IoT, Freescale iMX6-UL, Linux",
      "description": "Real time monitoring of patient weight and position by sensors embedded in the bed.",
      "imageurl": "stryker.jpeg"
    },
    {
      "no": 21,
      "orginal_no": 18,
      "title": "GE Mural Connect Hub ",
      "client": "GE Healthcare",
      "role": "Architect",
      "period": "March 2020 – August 2020",
      "teamSize": 8,
      "technologies": "VC++, C#, Perl, Webmin, Freescale iMX6Q, Linux, TFS 2015, Jenkins",
      "description": "Design and development of healthcare connectivity product which support ventilators, patient monitors and ECG systems.",
      "imageurl": "mural-connect-2_Compliance.png"
    },
    {
      "no": 16,
      "orginal_no": 19,
      "title": "Multi-Patient Viewer",
      "client": "GE Healthcare",
      "role": "Architect",
      "period": "Jan -2021 – Apr 2021",
      "teamSize": 7,
      "technologies": "Angular, Java Spring Boot, Docker, Kubernetes, HL7-FHIR, Jenkins",
      "description": "Hospital dashboard for doctors for prioritizing patients based on risk scores.",
      "imageurl": "GE_MPV.webp"
    },
    {
      "no": 17,
      "orginal_no": 20,
      "title": "Sustenance Data Analysis Platform ",
      "client": "GE Healthcare",
      "role": "Architect Consultant",
      "period": "Apr -2021 - July-2021",
      "teamSize": 8,
      "technologies": "Angular, Java Spring Boot, Kafka, AWS, Azure IoT",
      "description": "Solution for proactive maintenance of hospital ICU devices. Collect device logs and push to cloud from hospital environment. Detect potential risks and suggest mitigation plans.",
      "imageurl": "GE_ISP.svg"
    },
    {
      "no": 19,
      "orginal_no": 21,
      "title": "Infusion Pump",
      "client": "Baxter",
      "role": "Architect Consultant",
      "period": "March 2020 – July 2021",
      "teamSize": 8,
      "technologies": "C++, Qt 5.12, Qml, Freescale iMX6-UL, Linux",
      "description": "Next generation infusion pump medical device development program.",
      "imageurl": "baxter.jpeg"
    },
    {
      "no": 23,
      "orginal_no": 22,
      "title": "Mural Connect",
      "client": "GE Healthcare",
      "role": "Architect Consultant",
      "period": "Jan -2022 - Mar 2023",
      "teamSize": 12,
      "technologies": "Angular, Java Spring Boot, IBM Rhapsody",
      "description": "Enterprise solution for Hospital ICU Device Management which supports ~150 devices\n(Ventilators, Patient monitors, Anesthesia machine etc.).",
      "imageurl": "GE-mural_logo_concepts_onwhite.png"
    },
    {
      "no": 18,
      "orginal_no": 23,
      "title": "Mural Insights BI Platform",
      "client": "GE Healthcare",
      "role": "Architect Consultant",
      "period": "Jan -2022 - Mar 2023",
      "teamSize": 15,
      "technologies": "Angular, Java Spring Boot, Tableu, Azure Data Factory, ADLS, Data bricks, HL7",
      "description": "BI Platform for GE Healthcare with live dashboard for L&D ICU units by analyzing HL7 messages.",
      "imageurl": "GE-BI.png"
    },
    {
      "no": 25,
      "orginal_no": 24,
      "title": "Mural Perinatel and AI Integration. ",
      "client": "GE Healthcare",
      "role": "Architect",
      "period": "Nov -2022 - In progress",
      "teamSize": 9,
      "technologies": "Java, Flink, Python, TensorFlow, Docker, K8s, Azure Devops",
      "description": "Meternal infact care system and AI model integration.",
      "imageurl": "GE-perinatel.webp"
    },
    {
      "no": 24,
      "orginal_no": 25,
      "title": "MAC 600 ECG Machine",
      "client": "GE Healthcare",
      "role": "Architect Consultant",
      "period": "Feb -2023 - In progress",
      "teamSize": 25,
      "technologies": "C, Embedded Wizard, FreeRTOS, imxRT",
      "description": "Portable ECG machine with Wifi, LTE and Ethernet connectivity.",
      "imageurl": "GE-mac5.webp"
    }
  ]
};

export default projects;